/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DcAddsubEquation {
        "max": string;
        "min": string;
        "type": string;
    }
    interface DcEquationGrid {
        "max": string;
        "min": string;
        "quantity": string;
        "type": string;
    }
    interface DcMathSentence {
        "max": string;
        "min": string;
    }
    interface DcPageGenerator {
    }
    interface DcPageSentences {
    }
    interface DcSentanceStack {
        "max": string;
        "min": string;
        "quantity": string;
    }
}
declare global {
    interface HTMLDcAddsubEquationElement extends Components.DcAddsubEquation, HTMLStencilElement {
    }
    var HTMLDcAddsubEquationElement: {
        prototype: HTMLDcAddsubEquationElement;
        new (): HTMLDcAddsubEquationElement;
    };
    interface HTMLDcEquationGridElement extends Components.DcEquationGrid, HTMLStencilElement {
    }
    var HTMLDcEquationGridElement: {
        prototype: HTMLDcEquationGridElement;
        new (): HTMLDcEquationGridElement;
    };
    interface HTMLDcMathSentenceElement extends Components.DcMathSentence, HTMLStencilElement {
    }
    var HTMLDcMathSentenceElement: {
        prototype: HTMLDcMathSentenceElement;
        new (): HTMLDcMathSentenceElement;
    };
    interface HTMLDcPageGeneratorElement extends Components.DcPageGenerator, HTMLStencilElement {
    }
    var HTMLDcPageGeneratorElement: {
        prototype: HTMLDcPageGeneratorElement;
        new (): HTMLDcPageGeneratorElement;
    };
    interface HTMLDcPageSentencesElement extends Components.DcPageSentences, HTMLStencilElement {
    }
    var HTMLDcPageSentencesElement: {
        prototype: HTMLDcPageSentencesElement;
        new (): HTMLDcPageSentencesElement;
    };
    interface HTMLDcSentanceStackElement extends Components.DcSentanceStack, HTMLStencilElement {
    }
    var HTMLDcSentanceStackElement: {
        prototype: HTMLDcSentanceStackElement;
        new (): HTMLDcSentanceStackElement;
    };
    interface HTMLElementTagNameMap {
        "dc-addsub-equation": HTMLDcAddsubEquationElement;
        "dc-equation-grid": HTMLDcEquationGridElement;
        "dc-math-sentence": HTMLDcMathSentenceElement;
        "dc-page-generator": HTMLDcPageGeneratorElement;
        "dc-page-sentences": HTMLDcPageSentencesElement;
        "dc-sentance-stack": HTMLDcSentanceStackElement;
    }
}
declare namespace LocalJSX {
    interface DcAddsubEquation {
        "max"?: string;
        "min"?: string;
        "type"?: string;
    }
    interface DcEquationGrid {
        "max"?: string;
        "min"?: string;
        "quantity"?: string;
        "type"?: string;
    }
    interface DcMathSentence {
        "max"?: string;
        "min"?: string;
    }
    interface DcPageGenerator {
    }
    interface DcPageSentences {
    }
    interface DcSentanceStack {
        "max"?: string;
        "min"?: string;
        "quantity"?: string;
    }
    interface IntrinsicElements {
        "dc-addsub-equation": DcAddsubEquation;
        "dc-equation-grid": DcEquationGrid;
        "dc-math-sentence": DcMathSentence;
        "dc-page-generator": DcPageGenerator;
        "dc-page-sentences": DcPageSentences;
        "dc-sentance-stack": DcSentanceStack;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dc-addsub-equation": LocalJSX.DcAddsubEquation & JSXBase.HTMLAttributes<HTMLDcAddsubEquationElement>;
            "dc-equation-grid": LocalJSX.DcEquationGrid & JSXBase.HTMLAttributes<HTMLDcEquationGridElement>;
            "dc-math-sentence": LocalJSX.DcMathSentence & JSXBase.HTMLAttributes<HTMLDcMathSentenceElement>;
            "dc-page-generator": LocalJSX.DcPageGenerator & JSXBase.HTMLAttributes<HTMLDcPageGeneratorElement>;
            "dc-page-sentences": LocalJSX.DcPageSentences & JSXBase.HTMLAttributes<HTMLDcPageSentencesElement>;
            "dc-sentance-stack": LocalJSX.DcSentanceStack & JSXBase.HTMLAttributes<HTMLDcSentanceStackElement>;
        }
    }
}
