/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DcAddsubEquation {
        "max": string;
        "min": string;
        "type": string;
    }
    interface DcEquationGrid {
        "max": string;
        "min": string;
        "quantity": string;
        "type": string;
    }
    interface DcPageGenerator {
    }
}
declare global {
    interface HTMLDcAddsubEquationElement extends Components.DcAddsubEquation, HTMLStencilElement {
    }
    var HTMLDcAddsubEquationElement: {
        prototype: HTMLDcAddsubEquationElement;
        new (): HTMLDcAddsubEquationElement;
    };
    interface HTMLDcEquationGridElement extends Components.DcEquationGrid, HTMLStencilElement {
    }
    var HTMLDcEquationGridElement: {
        prototype: HTMLDcEquationGridElement;
        new (): HTMLDcEquationGridElement;
    };
    interface HTMLDcPageGeneratorElement extends Components.DcPageGenerator, HTMLStencilElement {
    }
    var HTMLDcPageGeneratorElement: {
        prototype: HTMLDcPageGeneratorElement;
        new (): HTMLDcPageGeneratorElement;
    };
    interface HTMLElementTagNameMap {
        "dc-addsub-equation": HTMLDcAddsubEquationElement;
        "dc-equation-grid": HTMLDcEquationGridElement;
        "dc-page-generator": HTMLDcPageGeneratorElement;
    }
}
declare namespace LocalJSX {
    interface DcAddsubEquation {
        "max"?: string;
        "min"?: string;
        "type"?: string;
    }
    interface DcEquationGrid {
        "max"?: string;
        "min"?: string;
        "quantity"?: string;
        "type"?: string;
    }
    interface DcPageGenerator {
    }
    interface IntrinsicElements {
        "dc-addsub-equation": DcAddsubEquation;
        "dc-equation-grid": DcEquationGrid;
        "dc-page-generator": DcPageGenerator;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dc-addsub-equation": LocalJSX.DcAddsubEquation & JSXBase.HTMLAttributes<HTMLDcAddsubEquationElement>;
            "dc-equation-grid": LocalJSX.DcEquationGrid & JSXBase.HTMLAttributes<HTMLDcEquationGridElement>;
            "dc-page-generator": LocalJSX.DcPageGenerator & JSXBase.HTMLAttributes<HTMLDcPageGeneratorElement>;
        }
    }
}
